### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by qiaojbao**

### CODE REVIEW

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 901a4b9cc0262cde61d1e1b5b7319d729b1fba21
<details><summary>CTS tests (Failed: 0/216210)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35422/73547 (48.2%)</li>
<li>Failed: 0/73547 (0.0%)</li>
<li>Not Supported: 38125/73547 (51.8%)</li><li>Warnings: 0/73547 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33115/69116 (47.9%)</li>
<li>Failed: 0/69116 (0.0%)</li>
<li>Not Supported: 36001/69116 (52.1%)</li><li>Warnings: 0/69116 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37683/73547 (51.2%)</li>
<li>Failed: 0/73547 (0.0%)</li>
<li>Not Supported: 35864/73547 (48.8%)</li><li>Warnings: 0/73547 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 901a4b9cc0262cde61d1e1b5b7319d729b1fba21
<details><summary>CTS tests (Failed: 0/216210)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35422/73547 (48.2%)</li>
<li>Failed: 0/73547 (0.0%)</li>
<li>Not Supported: 38125/73547 (51.8%)</li><li>Warnings: 0/73547 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33115/69116 (47.9%)</li>
<li>Failed: 0/69116 (0.0%)</li>
<li>Not Supported: 36001/69116 (52.1%)</li><li>Warnings: 0/69116 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37683/73547 (51.2%)</li>
<li>Failed: 0/73547 (0.0%)</li>
<li>Not Supported: 35864/73547 (48.8%)</li><li>Warnings: 0/73547 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Pull request closed without merging**
