### PR TITLE
Reinstate: Disable LLPC optimizations when VK_PIPELINE_CREATE_DISABLE…

### PR DESCRIPTION
**Pull request by dstutt**
…_OPTIMIZATION_BIT is set

This will allow the VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT bit to
have an effect for LLPC.

Re-submitting this change after it was reverted

### CODE REVIEW

**Review by JonCampbell407 — DISMISSED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit 6a34b0efa5d9ec6523d0b946ce445b90b3b3f348
<details><summary>CTS tests (Failed: 0/186422)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 36645/65226 (56.2%)</li>
<li>Failed: 0/65226 (0.0%)</li>
<li>Not Supported: 28581/65226 (43.8%)</li><li>Warnings: 0/65226 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30002/55970 (53.6%)</li>
<li>Failed: 0/55970 (0.0%)</li>
<li>Not Supported: 25968/55970 (46.4%)</li><li>Warnings: 0/55970 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 38946/65226 (59.7%)</li>
<li>Failed: 0/65226 (0.0%)</li>
<li>Not Supported: 26280/65226 (40.3%)</li><li>Warnings: 0/65226 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
@dstutt This does not seem to compile:
```
/vulkandriver/drivers/xgl/icd/api/pipeline_compiler.cpp:2635:15: error: ‘struct Vkgc::PipelineOptions’ has no member named ‘optimizationLevel’
 2635 |     pOptions->optimizationLevel = ((flags & VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT) != 0 ? 0 : 2);
      |               ^~~~~~~~~~~~~~~~~
```

**Comment by dstutt** [comment]
Not sure what is going on - the change is just an unrevert of an earlier one (which worked), plus the struct member does exist (gated by the llpc major version which is bumped in this change in importdefs)).

**Comment by Flakebi** [comment]
Adding a `cmake .` before the build in https://github.com/GPUOpen-Drivers/xgl/blob/6a34b0efa5d9ec6523d0b946ce445b90b3b3f348/tools/cache_creator/docker/check_xgl.Dockerfile#L39 could fix this.

**Comment by amdvlk-admin** [comment]
### Test summary for commit ea9a4b351058cb4168c5a374b328c0f92cb932a2
<details><summary>CTS tests (Failed: 0/186422)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 36645/65226 (56.2%)</li>
<li>Failed: 0/65226 (0.0%)</li>
<li>Not Supported: 28581/65226 (43.8%)</li><li>Warnings: 0/65226 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30002/55970 (53.6%)</li>
<li>Failed: 0/55970 (0.0%)</li>
<li>Not Supported: 25968/55970 (46.4%)</li><li>Warnings: 0/55970 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 38946/65226 (59.7%)</li>
<li>Failed: 0/65226 (0.0%)</li>
<li>Not Supported: 26280/65226 (40.3%)</li><li>Warnings: 0/65226 (0.0%)</li>
</ul></details>


</ul></details>

**Review by Flakebi — APPROVED** [review]

**Review by amdrexu — APPROVED** [review]

**Comment by dstutt** [comment]
Can someone approve/merge this and #157 (which this relies on) - I don't have permissions for either it would seem.

**Comment by amdrexu** [comment]
Done :)

**Comment by dstutt** [comment]
Thanks :)

**Pull request merged**
