### PR TITLE
[CI] Migrate to gcloud Artifact Registry

### PR DESCRIPTION
**Pull request by kuhar**
See the LLPC PR for more context: https://github.com/GPUOpen-Drivers/llpc/pull/1880.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit 274097410a372e1b64f27ff23ef470e931f1b808
<details><summary>CTS tests (Failed: 3/165995)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35418/63738 (55.6%)</li>
<li><details><summary>Failed: 1/63738 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.graphicsfuzz.cov-instruction-simplify-atanh-log-undefined
Stack trace: Script:
Fail

```
</p></details></li>

<li>Not Supported: 28319/63738 (44.4%)</li><li>Warnings: 0/63738 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 23700/38519 (61.5%)</li>
<li><details><summary>Failed: 1/38519 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.robustness.image_robustness.push.notemplate.rgba32f.unroll.nonvolatile.storage_image.no_fmt_qual.img.samples_1.3d.comp
Stack trace: Script:
Crash

```
</p></details></li>

<li>Not Supported: 14818/38519 (38.5%)</li><li>Warnings: 0/38519 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37583/63738 (59.0%)</li>
<li><details><summary>Failed: 1/63738 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.graphicsfuzz.cov-instruction-simplify-atanh-log-undefined
Stack trace: Script:
Fail

```
</p></details></li>

<li>Not Supported: 26154/63738 (41.0%)</li><li>Warnings: 0/63738 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 274097410a372e1b64f27ff23ef470e931f1b808
<details><summary>CTS tests (Failed: 2/179656)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35418/63738 (55.6%)</li>
<li><details><summary>Failed: 1/63738 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.graphicsfuzz.cov-instruction-simplify-atanh-log-undefined
Stack trace: Script:
Fail

```
</p></details></li>

<li>Not Supported: 28319/63738 (44.4%)</li><li>Warnings: 0/63738 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 27529/52180 (52.8%)</li>
<li>Failed: 0/52180 (0.0%)</li>
<li>Not Supported: 24651/52180 (47.2%)</li><li>Warnings: 0/52180 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37583/63738 (59.0%)</li>
<li><details><summary>Failed: 1/63738 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.graphicsfuzz.cov-instruction-simplify-atanh-log-undefined
Stack trace: Script:
Fail

```
</p></details></li>

<li>Not Supported: 26154/63738 (41.0%)</li><li>Warnings: 0/63738 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by Flakebi** [comment]
LGTM, can you also update the example command in https://github.com/GPUOpen-Drivers/xgl/blob/bbda9d38a9e979f2e669c5b942d04fab519f9359/tools/cache_creator/docker/check_xgl.Dockerfile#L5?

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 274097410a372e1b64f27ff23ef470e931f1b808
<details><summary>CTS tests (Failed: 0/179654)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35418/63737 (55.6%)</li>
<li>Failed: 0/63737 (0.0%)</li>
<li>Not Supported: 28319/63737 (44.4%)</li><li>Warnings: 0/63737 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 27529/52180 (52.8%)</li>
<li>Failed: 0/52180 (0.0%)</li>
<li>Not Supported: 24651/52180 (47.2%)</li><li>Warnings: 0/52180 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37679/63737 (59.1%)</li>
<li>Failed: 0/63737 (0.0%)</li>
<li>Not Supported: 26058/63737 (40.9%)</li><li>Warnings: 0/63737 (0.0%)</li>
</ul></details>


</ul></details>

**Review by vettoreldaniele — APPROVED** [review]

**Review by Flakebi — APPROVED** [review]

**Review by amdrexu — APPROVED** [review]

**Comment by amdvlk-admin** [comment]
### Test summary for commit c5194f0c32600772f2e1a1d578450082018f3511
<details><summary>CTS tests (Failed: 0/179654)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35418/63737 (55.6%)</li>
<li>Failed: 0/63737 (0.0%)</li>
<li>Not Supported: 28319/63737 (44.4%)</li><li>Warnings: 0/63737 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 27529/52180 (52.8%)</li>
<li>Failed: 0/52180 (0.0%)</li>
<li>Not Supported: 24651/52180 (47.2%)</li><li>Warnings: 0/52180 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37679/63737 (59.1%)</li>
<li>Failed: 0/63737 (0.0%)</li>
<li>Not Supported: 26058/63737 (40.9%)</li><li>Warnings: 0/63737 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by kuhar** [comment]
@amdrexu Could you merge this please?

**Comment by amdrexu** [comment]
Done

**Comment by qiaojbao** [comment]
retest this please

**Pull request merged**
