### PR TITLE
Use external synchronization for multi process shared memory

### PR DESCRIPTION
**Pull request by jfthibert**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by JaxLinAMD** [comment]
ok to test

**Comment by JaxLinAMD** [comment]
retest this please

**Review by JonCampbell407 — APPROVED** [review]

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit c24918a1a4e53767e9f83849078bc9af3887de4f
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>LLPC: dev 4089917811c05479d25b15066508e40505b1232a</li>
<li>PAL: dev 95494513896a18924512ef426834e4c49967da56</li>
<li>SPVGEN: dev 6e35eab398b519b8056a13a57dafc6c64b3df13a</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev fef6a69e1cc922638cd248e8d73670df38fa63a1</li>
</ul></details>

<details><summary>CTS tests (Failed: 2/177789)</summary><ul><li>Built with version 1.2.2.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 27608/59232 (46.6%)</li>
<li>Failed: 0/59232 (0.0%)</li>
<li>Skipped: 31624/59232 (53.4%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 27606/59232 (46.6%)</li>
<li><details><summary>Failed: 1/59232 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.spirv_assembly.instruction.graphics.opname_abuse.b_is_gl_Position_vert
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 31625/59232 (53.4%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 26812/59325 (45.2%)</li>
<li><details><summary>Failed: 1/59325 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.pipeline.creation_feedback.graphics_tests.vertex_stage_fragment_stage_no_cache
Stack trace: Flake
```
</p></details></li>

<li>Skipped: 32512/59325 (54.8%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Timeout or crash</li>

</ul></details>


</ul></details>

**Pull request merged**
