### PR TITLE
Switch Cache Creator unit tests to gtest/gmock

### PR DESCRIPTION
**Pull request by kuhar**
Allow tests to be executed with lit (`ninja check-cache-creator-units`).

This is keep consistent with LLPC and LLVM.

### CODE REVIEW

**Comment by kuhar** [comment]
Note that this also requires https://github.com/GPUOpen-Drivers/llpc/pull/1340

**Comment by amdvlk-admin** [comment]
### Test summary for commit 37f166d85607f5e149fcbf21b483d977a1efafc9
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>LLPC: dev b8b1be8a3cd20c67f494665c1c31c8b38f8a2818</li>
<li>PAL: dev 408fbcdd1249dea3469bbd3426c29ca344386d6f</li>
<li>SPVGEN: dev bb3da8bc00bcf4373d563bf9b3c74a80a8b28fe6</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 53de8fec5020e6fec5411a795ce8c38fae6516ac</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/228032)</summary><ul><li>Built with version 1.2.5.2</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 32108/57008 (56.3%)</li>
<li>Failed: 0/57008 (0.0%)</li>
<li>Not Supported: 24900/57008 (43.7%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 32108/57008 (56.3%)</li>
<li>Failed: 0/57008 (0.0%)</li>
<li>Not Supported: 24900/57008 (43.7%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 32488/57008 (57.0%)</li>
<li>Failed: 0/57008 (0.0%)</li>
<li>Not Supported: 24520/57008 (43.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 35419/57008 (62.1%)</li>
<li>Failed: 0/57008 (0.0%)</li>
<li>Not Supported: 21589/57008 (37.9%)</li>
</ul></details>


</ul></details>

**Comment by JaxLinAMD** [comment]
Hi @kuhar there is some error in github actions

**Comment by kuhar** [comment]
@JaxLinAMD this is expected, see https://github.com/GPUOpen-Drivers/xgl/pull/123#issuecomment-889903858

**Comment by kuhar** [comment]
@JaxLinAMD this should have been merged *after* GPUOpen-Drivers/llpc#1340

Could you either ralso merge GPUOpen-Drivers/llpc#1340 or rever this PR?

**Comment by JaxLinAMD** [comment]
I 'll merge 1340

**Pull request merged**
