### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by qiaojbao**

### CODE REVIEW

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfce8c546cac8fa64dd7f0a94587aeabfa029b4b
<details><summary>CTS tests (Failed: 0/73567)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 38675/73567 (52.6%)</li>
<li>Failed: 0/73567 (0.0%)</li>
<li>Not Supported: 34892/73567 (47.4%)</li><li>Warnings: 0/73567 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfce8c546cac8fa64dd7f0a94587aeabfa029b4b
<details><summary>CTS tests (Failed: 0/73567)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 38675/73567 (52.6%)</li>
<li>Failed: 0/73567 (0.0%)</li>
<li>Not Supported: 34892/73567 (47.4%)</li><li>Warnings: 0/73567 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfce8c546cac8fa64dd7f0a94587aeabfa029b4b
<details><summary>CTS tests (Failed: 1/216287)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35463/73567 (48.2%)</li>
<li>Failed: 0/73567 (0.0%)</li>
<li>Not Supported: 38104/73567 (51.8%)</li><li>Warnings: 0/73567 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33155/69153 (47.9%)</li>
<li><details><summary>Failed: 1/69153 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.api.copy_and_blit.core.buffer_to_buffer.whole
Stack trace: Flake
```
</p></details></li>

<li>Not Supported: 35997/69153 (52.1%)</li><li>Warnings: 0/69153 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37728/73567 (51.3%)</li>
<li>Failed: 0/73567 (0.0%)</li>
<li>Not Supported: 35839/73567 (48.7%)</li><li>Warnings: 0/73567 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfce8c546cac8fa64dd7f0a94587aeabfa029b4b
<details><summary>CTS tests (Failed: 0/216059)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35298/73410 (48.1%)</li>
<li>Failed: 0/73410 (0.0%)</li>
<li>Not Supported: 38112/73410 (51.9%)</li><li>Warnings: 0/73410 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 33017/69239 (47.7%)</li>
<li>Failed: 0/69239 (0.0%)</li>
<li>Not Supported: 36222/69239 (52.3%)</li><li>Warnings: 0/69239 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37553/73410 (51.2%)</li>
<li>Failed: 0/73410 (0.0%)</li>
<li>Not Supported: 35857/73410 (48.8%)</li><li>Warnings: 0/73410 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfce8c546cac8fa64dd7f0a94587aeabfa029b4b
<details><summary>CTS tests (Failed: 35/73409)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Gfx103</summary><ul>

<li>Passed: 38490/73409 (52.4%)</li>
<li><details><summary>Failed: 35/73409 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.b8g8r8a8_snorm_b8g8r8a8_srgb_draw_copy_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.b8g8r8a8_snorm_r8g8b8a8_snorm_draw_load_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.b8g8r8a8_snorm_r8g8b8a8_snorm_store_copy_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.b8g8r8a8_snorm_r8g8b8a8_snorm_store_load_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.b8g8r8a8_srgb_r8g8b8a8_unorm_copy_load_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.b8g8r8a8_unorm_b8g8r8a8_srgb_draw_copy_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.b8g8r8a8_unorm_r8g8b8a8_unorm_copy_texture_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.b8g8r8a8_unorm_r8g8b8a8_unorm_draw_texture_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.r8g8b8a8_snorm_b8g8r8a8_snorm_draw_copy_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.r8g8b8a8_snorm_r8g8b8a8_srgb_clear_copy_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.r8g8b8a8_snorm_r8g8b8a8_unorm_store_copy_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.r8g8b8a8_srgb_b8g8r8a8_snorm_copy_copy_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.r8g8b8a8_srgb_b8g8r8a8_srgb_draw_copy_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.r8g8b8a8_srgb_r8g8b8a8_snorm_clear_copy_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.r8g8b8a8_srgb_r8g8b8a8_snorm_copy_load_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.r8g8b8a8_srgb_r8g8b8a8_snorm_draw_load_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.r8g8b8a8_srgb_r8g8b8a8_snorm_draw_texture_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.r8g8b8a8_srgb_r8g8b8a8_snorm_store_load_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.r8g8b8a8_srgb_r8g8b8a8_unorm_clear_copy_format_list
Stack trace: Crash

FAILURE: dEQP-VK.image.swapchain_mutable.wayland.2d.r8g8b8a8_srgb_r8g8b8a8_unorm_store_copy_format_list
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 34884/73409 (47.5%)</li><li>Warnings: 0/73409 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfce8c546cac8fa64dd7f0a94587aeabfa029b4b
<details><summary>CTS tests (Failed: 0/0)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Timeout or crash</li>

</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfce8c546cac8fa64dd7f0a94587aeabfa029b4b
<details><summary>CTS tests (Failed: 0/73375)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38490/73375 (52.5%)</li>
<li>Failed: 0/73375 (0.0%)</li>
<li>Not Supported: 34885/73375 (47.5%)</li><li>Warnings: 0/73375 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfce8c546cac8fa64dd7f0a94587aeabfa029b4b
<details><summary>CTS tests (Failed: 2/288637)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 0/73202 (0.0%)</li>
<li>Failed: 0/73202 (0.0%)</li>
<li>Not Supported: 73202/73202 (100.0%)</li><li>Warnings: 0/73202 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 0/69031 (0.0%)</li>
<li>Failed: 0/69031 (0.0%)</li>
<li>Not Supported: 69031/69031 (100.0%)</li><li>Warnings: 0/69031 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37553/73202 (51.3%)</li>
<li><details><summary>Failed: 1/73202 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.graphicsfuzz.cov-instruction-simplify-atanh-log-undefined
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 35648/73202 (48.7%)</li><li>Warnings: 0/73202 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38491/73202 (52.6%)</li>
<li><details><summary>Failed: 1/73202 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.graphicsfuzz.cov-instruction-simplify-atanh-log-undefined
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 34710/73202 (47.4%)</li><li>Warnings: 0/73202 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfce8c546cac8fa64dd7f0a94587aeabfa029b4b
<details><summary>CTS tests (Failed: 0/289743)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 35298/73498 (48.0%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 38200/73498 (52.0%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx9</summary><ul>

<li>Passed: 33017/69327 (47.6%)</li>
<li>Failed: 0/69327 (0.0%)</li>
<li>Not Supported: 36310/69327 (52.4%)</li><li>Warnings: 0/69327 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 37553/73420 (51.1%)</li>
<li>Failed: 0/73420 (0.0%)</li>
<li>Not Supported: 35867/73420 (48.9%)</li><li>Warnings: 0/73420 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38491/73498 (52.4%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 35007/73498 (47.6%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfce8c546cac8fa64dd7f0a94587aeabfa029b4b
<details><summary>CTS tests (Failed: 0/73370)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Timeout or crash</li>

</ul></details>

<details open><summary>Rhel 8.6, Gfx8</summary><ul>

<li>Passed: 37494/73370 (51.1%)</li>
<li>Failed: 0/73370 (0.0%)</li>
<li>Not Supported: 35876/73370 (48.9%)</li><li>Warnings: 0/73370 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfce8c546cac8fa64dd7f0a94587aeabfa029b4b
<details><summary>CTS tests (Failed: 0/138554)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 9.0, Gfx9</summary><ul>

<li>Passed: 36014/69277 (52.0%)</li>
<li>Failed: 0/69277 (0.0%)</li>
<li>Not Supported: 33263/69277 (48.0%)</li><li>Warnings: 0/69277 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 22.04, Gfx9</summary><ul>

<li>Passed: 36015/69277 (52.0%)</li>
<li>Failed: 0/69277 (0.0%)</li>
<li>Not Supported: 33262/69277 (48.0%)</li><li>Warnings: 0/69277 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit cfce8c546cac8fa64dd7f0a94587aeabfa029b4b
<details><summary>CTS tests (Failed: 0/72463)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel srdcvk, Gfx8or9</summary><ul>

<li>Passed: 36222/72463 (50.0%)</li>
<li>Failed: 0/72463 (0.0%)</li>
<li>Not Supported: 36241/72463 (50.0%)</li><li>Warnings: 0/72463 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request closed without merging**
