### PR TITLE
-Wdelete-non-abstract-non-virtual-dtor is clang specific warnings

### PR DESCRIPTION
**Pull request by JaxLinAMD**

### CODE REVIEW

**Comment by JaxLinAMD** [comment]
@dstutt @trenouf could you please take a look at this build error in CI docker build?

/vulkandriver/drivers/llpc/llpc/../../llvm-project/llvm/include/llvm/Object/ELFObjectFile.h:847:23: error: redundant move in return statement [-Werror=redundant-move]
  847 |     return std::move(E);

**Comment by dstutt** [comment]
[AMD Official Use Only - Internal Distribution Only]

Adding @Renouf, ***@***.***>
________________________________

**Comment by dstutt** [comment]
[AMD Official Use Only - Internal Distribution Only]

This happens when building the cache creator tool.

-tpr

From: David Stuttard ***@***.***>
Date: Wednesday, 14 April 2021 at 11:03
To: GPUOpen-Drivers/xgl ***@***.***>, GPUOpen-Drivers/xgl ***@***.***>, "Renouf, Tim" ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [GPUOpen-Drivers/xgl] -Wdelete-non-abstract-non-virtual-dtor is clang specific warnings (#110)


[AMD Official Use Only - Internal Distribution Only]

Adding @Renouf, ***@***.***>
________________________________

**Comment by trenouf** [comment]
I reproduced this with -DXGL_BUILD_CACHE_CREATOR=ON -DICD_ANALYSIS_WARNINGS_AS_ERRORS=ON. But I got a bunch of other warnings-as-errors too.

To use ICD_ANALYSIS_WARNINGS_AS_ERRORS, you'll need to disable some more warnings-as-errors:

```
diff --git a/cmake/XglCompilerOptions.cmake b/cmake/XglCompilerOptions.cmake
index 5e562aa..bdfbfd5 100644
--- a/cmake/XglCompilerOptions.cmake
+++ b/cmake/XglCompilerOptions.cmake
@@ -221,11 +221,14 @@ function(xgl_compiler_options TARGET)
         if(ICD_ANALYSIS_WARNINGS_AS_ERRORS)
             target_compile_options(${TARGET} PRIVATE
                 -Werror
+                -Wno-error=class-memaccess
                 -Wno-error=comment
-                -Wno-error=delete-non-abstract-non-virtual-dtor
+                -Wno-error=extra
                 -Wno-error=ignored-qualifiers
+                -Wno-error=maybe-uninitialized
                 -Wno-error=missing-braces
                 -Wno-error=pointer-arith
+                -Wno-error=redundant-move
                 -Wno-error=unused-parameter
             )
         endif()
@@ -272,6 +275,7 @@ function(xgl_compiler_options TARGET)
                 # Output with color if in terminal: https://github.com/ninja-build/ninja/wiki/FAQ
                 -fcolor-diagnostics
 
+                -Wno-error=delete-non-abstract-non-virtual-dtor
                 -Wthread-safety
             )
         endif()
```

I was using gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Comment by kuhar** [comment]
@trenouf should we just not run without warnings as errors in the CI?
I think @Flakebi enabled this in the CI: https://github.com/GPUOpen-Drivers/llpc/pull/689 a while back.

**Comment by dstutt** [comment]
> @trenouf should we just not run without warnings as errors in the CI?
> I think @Flakebi enabled this in the CI: [GPUOpen-Drivers/llpc#689](https://github.com/GPUOpen-Drivers/llpc/pull/689) a while back.

In general I think warnings as errors is good - but perhaps there's just too many moving parts to get any sort of stability here.

We're using quite a lot of different compilers in the different test systems and they all produce different warnings - it's tricky to expect a developer to pick them all up. If we just try and fix and/or notify as appropriate when we see them, then that might be sufficient?

I guess I'm saying that I agree - we should turn off warnings as errors.

**Comment by kuhar** [comment]
I opened a PR that disabled Werror in CI builds: https://github.com/GPUOpen-Drivers/llpc/pull/1216

**Comment by kuhar** [comment]
Note that this PR should still go in, because it's not a valid gcc option and it makes builds fail even without Werror.

**Review by dstutt — APPROVED** [review]
LGTM

**Comment by dstutt** [comment]
retest this please

**Comment by Renouf** [comment]
Hi there, you know you're emailing this to the wrong Tim Renouf right? :-)

Tim.

**Comment by JaxLinAMD** [comment]
Hi @Renouf did you receive a "retest this please" message?

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by Renouf** [comment]
Yes

**Comment by amdvlk-admin** [comment]
### Test summary for commit 4b11a81c2b15db3d9c8058c1a43b46d019e27d12
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 7387247eb9889ddcabbc1053b9c2052e253b088e</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>LLPC: dev 1315bcfa43864b5cb4554533f8b7e3520cbbabb6</li>
<li>PAL: dev 56f2e165b889bd7ca147ff853e6f1372ed90d4fe</li>
<li>SPVGEN: dev 4846370016de9775b7518b51c08260387a7367c4</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 59efb265ed3fd48137fed3282b7782742b88b2e1</li>
</ul></details>

<details><summary>CTS tests (Failed: 2/222275)</summary><ul><li>Built with version 1.2.5.1</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 30438/55574 (54.8%)</li>
<li>Failed: 0/55574 (0.0%)</li>
<li>Not supported: 25136/55574 (45.2%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 30437/55574 (54.8%)</li>
<li>Failed: 0/55574 (0.0%)</li>
<li>Not supported: 25137/55574 (45.2%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 30630/55553 (55.1%)</li>
<li><details><summary>Failed: 1/55553 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.basic.event.device_set_reset
Stack trace: Script:
synchronizationWrapper->queueSubmit(queue, DE_NULL): VK_ERROR_UNKNOWN at vktSynchronizationBasicEventTests.cpp:117

```
</p></details></li>

<li>Not supported: 24922/55553 (44.9%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx103</summary><ul>

<li>Passed: 34000/55574 (61.2%)</li>
<li><details><summary>Failed: 1/55574 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.synchronization.basic.event.device_set_reset
Stack trace: Script:
synchronizationWrapper->queueSubmit(queue, DE_NULL): VK_ERROR_UNKNOWN at vktSynchronizationBasicEventTests.cpp:117

```
</p></details></li>

<li>Not supported: 21573/55574 (38.8%)</li>
</ul></details>


</ul></details>

**Comment by dstutt** [comment]
Sorry @Renouf 
Adding @trenouf

**Comment by Renouf** [comment]
Cheers, I'm actually a software engineer at Air New Zealand, not so hot on
GPU development. :-)

**Pull request closed without merging**
