### PR TITLE
Disable LLPC optimizations when VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT is set

### PR DESCRIPTION
**Pull request by s-perron**
This will allow the VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT bit to
have an effect for LLPC.

### CODE REVIEW

**Comment by s-perron** [comment]
We need to wait for https://github.com/GPUOpen-Drivers/llpc/pull/1673 to be merged.

**Review by JonCampbell407 — APPROVED** [review]

**Comment by s-perron** [comment]
retest this please

**Comment by s-perron** [comment]
@JaxLinAMD I can't see the results for the Jenkins build.  Let me know if there is a problem.  Otherwise, can this be merged?

**Comment by JaxLinAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit da0c094a62d127a5837f51dc926578005465c858
<details><summary>Driver commits used in build</summary><ul>

<li>CWPACK: amd-master 39f8940199e60c44d4211cf8165dfd12876316fa</li>
<li>METROHASH: amd-master 3c566dd9cda44ca7fd97659e0b53ac953f9037d2</li>
<li>LLPC: dev 5837abb209dfed4d4bb0dd7e1d524148961a5c8d</li>
<li>PAL: dev 2483d46fa27c30502e497ea169ee53b142e9fa06</li>
<li>SPVGEN: dev fa39b110650bc72fd7fda54af621e69306036888</li>
<li>LLVM-PROJECT: amd-gfx-gpuopen-dev 2a87cb67e0180322832e722db8a4c53a5fc4e867</li>
</ul></details>

<details><summary>CTS tests (Failed: 0/203169)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Rhel 8.2, Gfx10</summary><ul>

<li>Passed: 38237/67723 (56.5%)</li>
<li>Failed: 0/67723 (0.0%)</li>
<li>Not Supported: 29486/67723 (43.5%)</li><li>Warnings: 0/67723 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Gfx9</summary><ul>

<li>Passed: 38075/67723 (56.2%)</li>
<li>Failed: 0/67723 (0.0%)</li>
<li>Not Supported: 29648/67723 (43.8%)</li><li>Warnings: 0/67723 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 20.04, Gfx8</summary><ul>

<li>Passed: 39235/67723 (57.9%)</li>
<li>Failed: 0/67723 (0.0%)</li>
<li>Not Supported: 28488/67723 (42.1%)</li><li>Warnings: 0/67723 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
