### PR TITLE
Jenkins PR Test

### PR DESCRIPTION
**Pull request by chenjas**
Test with Jenkins CI functionality.

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
Can one of the admins verify this patch?

**Comment by amdvlk-admin** [comment]
### Test summary for commit 04bda2734d3d416938a9f0b28ca1892497c0b79d
<details><summary>Driver branches used in build</summary><p>

* LLPC: _dev_
* PAL: _dev_
* LLVM: _amd-vulkan-dev_
</p></details>

#### CTS tests (built with branch _master_)
<details><summary>ubuntu, 18-04, ellesmere</summary><p>

* Passed: 314490/314534 (100.0%)
* Failed: 44/314534 (0.0%)
* Failures:
```
FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.graphics.subgroupall_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.graphics.subgroupany_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_int
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec4
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupall_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupany_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_uvec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_uvec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_uvec4
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_float
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_vec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_vec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_vec4
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_double
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_dvec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_dvec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_dvec4
Stack trace: Failed!
...

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_bool
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_bvec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_bvec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_bvec4
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_int_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_ivec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_ivec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_ivec4_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uint_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uvec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uvec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uvec4_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_float_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_vec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_vec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_vec4_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_double_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_dvec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_dvec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_dvec4_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_bool_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_bvec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_bvec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_bvec4_fragment
Stack trace: Failed!
```
</p></details>

**Comment by amdvlk-admin** [comment]
ok to test

**Comment by amdvlk-admin** [comment]
test this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 04bda2734d3d416938a9f0b28ca1892497c0b79d
<details><summary>Driver branches used in build</summary><p>

* LLPC: _dev_
* PAL: _dev_
* LLVM: _amd-vulkan-dev_
</p></details>

#### CTS tests (built with branch _master_)
<details><summary>ubuntu, 18-04, ellesmere</summary><p>

* Passed: 314490/314534 (100.0%)
* Failed: 44/314534 (0.0%)
* Failures:
```
FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.graphics.subgroupall_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.graphics.subgroupany_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_int
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec4
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupall_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupany_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_uvec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_uvec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_uvec4
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_float
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_vec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_vec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_vec4
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_double
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_dvec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_dvec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_dvec4
Stack trace: Failed!
...

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_bool
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_bvec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_bvec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_bvec4
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_int_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_ivec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_ivec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_ivec4_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uint_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uvec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uvec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uvec4_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_float_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_vec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_vec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_vec4_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_double_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_dvec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_dvec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_dvec4_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_bool_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_bvec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_bvec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_bvec4_fragment
Stack trace: Failed!
```
</p></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 04bda2734d3d416938a9f0b28ca1892497c0b79d
<details><summary>Driver branches used in build</summary><p>

* LLPC: _dev_
* PAL: _dev_
* LLVM: _amd-vulkan-dev_
</p></details>

#### CTS tests (built with branch _master_)
<details><summary>ubuntu, 18-04, ellesmere</summary><p>

* Passed: 314490/314534 (100.0%)
* Failed: 44/314534 (0.0%)
* Failures:
```
FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.graphics.subgroupall_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.graphics.subgroupany_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_int
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_ivec4
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupall_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupany_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_uint
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_uvec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_uvec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_uvec4
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_float
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_vec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_vec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_vec4
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_double
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_dvec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_dvec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_dvec4
Stack trace: Failed!
...

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_bool
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_bvec2
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_bvec3
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.compute.subgroupallequal_bvec4
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_int_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_ivec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_ivec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_ivec4_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uint_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uvec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uvec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_uvec4_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_float_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_vec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_vec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_vec4_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_double_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_dvec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_dvec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_dvec4_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_bool_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_bvec2_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_bvec3_fragment
Stack trace: Failed!

FAILURE: ubuntu_18-04_ellesmere.dEQP-VK.subgroups.vote.frag_helper.subgroupallequal_bvec4_fragment
Stack trace: Failed!
```
</p></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit 04bda2734d3d416938a9f0b28ca1892497c0b79d
<details open><summary>Driver branches used in build</summary><ul>

<li>LLPC: dev 41c154f</li>
<li>PAL: dev d939792</li>
<li>SPVGEN: dev 328a099</li>
<li>LLVM: amd-vulkan-dev e594994ad72</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>ubuntu, 18-04, ellesmere</summary><ul>

<li>Passed: 312610/312610 (100.0%)</li>
<li>Failed: 0/312610 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 04bda2734d3d416938a9f0b28ca1892497c0b79d
<details><summary>Driver branches used in build</summary><p>

* LLPC: _dev_
* PAL: _dev_
* SPVGEN: _dev_
* LLVM: _amd-vulkan-dev_
</p></details>

#### CTS tests (built with branch _Vulkan-CTS-1.1.1.2-cherry-picks_)
<details><summary>ubuntu, 18-04, ellesmere</summary><p>

* Passed: 312610/312610 (100.0%)
* Failed: 0/312610 (0.0%)
</p></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit 04bda2734d3d416938a9f0b28ca1892497c0b79d
<details><summary>Driver branches used in build</summary><p>

* LLPC: _dev_
* PAL: _dev_
* SPVGEN: _dev_
* LLVM: _amd-vulkan-dev_
</p></details>

#### CTS tests (built with branch _Vulkan-CTS-1.1.1.2-cherry-picks_)
<details><summary>ubuntu, 18-04, ellesmere</summary><p>

* Passed: 312610/312610 (100.0%)
* Failed: 0/312610 (0.0%)
</p></details>

**Pull request closed without merging**
