### PR TITLE
cmake: Enabled LLVM_INCLUDE_UTILS as required by lit testing

### PR DESCRIPTION
**Pull request by trenouf**
Without this, cmake complains that it cannot find the dependency 'not'.
This has been broken since I integrated llpc lit testing. Not sure why
no test run noticed. I did not notice locally because I was manually
specifying -DLLVM_INCLUDE_UTILS=1.

Also moved a comment that had accidentally got detached from what it
referred to. It turns out that you cannot use LLVM_OPTIMIZED_TABLEGEN in
an AMDVLK cmake build if you have a non-standard source layout so you
need to specify -DXGL_LLVM_SRC_PATH etc, because LLVM's cmake files
invoke a whole new cmake for the NATIVE target, and it does not pass
through XGL_LLVM_SRC_PATH etc.

### CODE REVIEW

**Comment by trenouf** [comment]
Ping.

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by JacobHeAMD** [comment]
sorry, I forgot it. Let's wait for the Jenkins test.

**Comment by trenouf** [comment]
Jacob, this is in the XGL repository. That does not run tests does it?

**Comment by JacobHeAMD** [comment]
It will trigger the test,but there is an access error  to srdc artifacts server for all of Jenkins tests, including llpc. Already sent an Email to infrastructure team to take a look.

**Comment by amdvlk-admin** [comment]
### Test summary for commit f4468781d5386f4e2c2104cb186e1cfecbfcd5f4
<details open><summary>Driver commits used in build</summary><ul>

<li>LLPC: dev f92e12ca756e48ae8b53b5c4d58c5682d025e2eb</li>
<li>PAL: dev b563d58ad6dc7c2daee9b73801dcc1321686b73b</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>LLVM: amd-vulkan-dev 1ca248e6fc6d4d15491756f92f4da139222ef3ca</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Vega20</summary><ul>

<li>Passed: 253561/253562 (100.0%)</li>
<li><details><summary>Failed: 1/253562 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.wsi.xlib.swapchain.render.basic
Stack trace: Timeout or crahsed
```
</p></details></li>


</ul></details>


</ul></details>

**Comment by JacobHeAMD** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit f4468781d5386f4e2c2104cb186e1cfecbfcd5f4
<details open><summary>Driver commits used in build</summary><ul>

<li>LLPC: dev f92e12ca756e48ae8b53b5c4d58c5682d025e2eb</li>
<li>PAL: dev b563d58ad6dc7c2daee9b73801dcc1321686b73b</li>
<li>SPVGEN: dev 5378c7618a2a3bf60ba01a86db980930e8581146</li>
<li>LLVM: amd-vulkan-dev 1ca248e6fc6d4d15491756f92f4da139222ef3ca</li>
</ul></details>

<details open><summary>CTS tests (built with branch Vulkan-CTS-1.1.1.2-cherry-picks)</summary><ul>


<details open><summary>Rhel 7.6, Vega10</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Ellesmere</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>

<details open><summary>Ubuntu 18.04, Vega20</summary><ul>

<li>Passed: 312622/312622 (100.0%)</li>
<li>Failed: 0/312622 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request merged**
